# @package _global_
defaults:
  - override /model: rnndet

model:
  backbone:
    name: ETRNN
    compile:
      enable: False
      args:
        mode: reduce-overhead
    feature_extractor:
      height: ~
      width: ~
      embed_dim: 32
      embed_norm: True
      drop_out: 0
      drop_path_rate: 0
      conv_ks_list: [5, 3, 3, 3]
      depth_list: [1, 1, 1, 1]
      k_nearest_list: [8, 16, 16, 16]
      mlp_ratio_list: [4, 4, 4, 4]
      global_step_list: [16, 16, 8, 4]
      down_stride_list: [4, 4, 4, -1]
      out_strides: [-1, 8, 16, 32]
    stage:
      lstm:
        dws_conv: False
        dws_conv_only_hidden: True
        dws_conv_kernel_size: 3
        drop_cell_update: 0
  fpn:
    name: PAFPN
    compile:
      enable: False
      args:
        mode: reduce-overhead
    depth: 0.67 # round(depth * 3) == num bottleneck blocks
    # stage 1 is the first and len(num_layers) is the last
    in_stages: [2, 3, 4]
    depthwise: False
    act: "silu"
  head:
    name: YoloX
    compile:
      enable: False
      args:
        mode: reduce-overhead
    depthwise: False
    act: "silu"
  postprocess:
    confidence_threshold: 0.1
    nms_threshold: 0.45
